---
name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
      - name: Setup JAR to DMG convert script
        uses: actions/checkout@master
        with:
          name: Jorl17/jar2app  <-- clone https://github.com/Jorl17/jar2app
        run: |
          cd jar2app
          chmod +x install.sh uninstall.sh
          sudo ./install.sh
          cd ..
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create JAR
        run: |
          echo ${{ github.sha }} > Release.txt
          mvn package
          cp target/JPaint-0.0.1-jar-with-dependencies.jar ./JPaint-${{ env.RELEASE_VERSION }}.jar
          git clone https://github.com/Jorl17/jar2app
          jar2app JPaint-${{ env.RELEASE_VERSION }}.jar
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JPaint-${{ env.RELEASE_VERSION }}.jar,
            JPaint-${{ env.RELEASE_VERSION }}.app,
            Release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
