---
name: Publish

on:
  create:
    tags:
      - v*
      -

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create JAR
        run: |
          echo ${{ github.sha }} > Release.txt
          mvn package
          cp target/JPaint-0.0.1-jar-with-dependencies.jar ./JPaint-${{ env.RELEASE_VERSION }}.jar
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JPaint-${{ env.RELEASE_VERSION }}.jar
            Release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
